In [1]:
import numpy as np 


In [3]:
a=np.arange(9).reshape(3,3)
b=np.arange(9).reshape(3,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#scenerio 1 
a+b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [7]:
#scenerio 2 
c=np.arange(9).reshape(3,3)
d=np.arange(3).reshape(1,3)
print(c)
print(d)
c+d

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [8]:
#BroadCasting: arithmetic operations on different sizes of array


In [ ]:
#Rules For Broadcasting
#if they are of same size
#if any one of them is 1 and the other one on each is same (same dimesion)
#reverse (1,3)(3,1) will also work 
#if one is [1,1]
