In [3]:
import numpy as np 
arr1=np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr2=np.array([1,2,3,4,5])
arr2[2:4]

array([3, 4])

In [13]:
arr1[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
#extracting third column 
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [16]:
arr1[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [17]:
#extracting 9 10 13 14 
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [18]:
arr1[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [20]:
#iteration 
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
for i in np.nditer(arr1):
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
